# Generated by Django 5.2.4 on 2025-08-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_stock', models.IntegerField()),
                ('fecha_creacion', models.DateField()),
                ('fecha_ultima_modificacion', models.DateField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
